# SPDX-License-Identifier: MIT
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring:kosmoo
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs: ["get", "list", "watch"]