# SPDX-License-Identifier: MIT
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring:kosmoo
subjects:
- kind: ServiceAccount
  name: kosmoo
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: monitoring:kosmoo
  apiGroup: rbac.authorization.k8s.io
